name: Deploy to GCP App Engine

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Generate env from secrets
              run: echo ${{ secrets.CHAPTER_5_GCP_ENV }} > ./chapter-5/topic-1/.env

            - id: "auth"
              uses: "google-github-actions/auth@v2"
              with:
                  credentials_json: "${{ secrets.CHAPTER_5_GCP_SA_KEY }}"

            - name: "Set up Cloud SDK"
              uses: "google-github-actions/setup-gcloud@v2"
              with:
                  project_id: ${{ secrets.CHAPTER_5_PROJECT_ID}}

            - name: Deploy to App Engine
              run: |
                  gcloud app deploy ./chapter-5/topic-1/app.yaml --quiet
